name: Generate Sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://pathargata-digital-community-ltd.github.io/Website/
        drop-html-extension: true

    - name: Commit and push the sitemap
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add sitemap.xml
        git diff --staged --quiet || git commit -m "Automatically generate sitemap"
        git push
